services:
  mysql-server:
    image: mysql:8
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 8s
      retries: 3
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - network-mysql

  mysql-client:
    image: phpmyadmin
    container_name: mysql-client
    ports:
      - "8080:80"
    depends_on:
      mysql-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 8s
      retries: 3
    environment:
      PMA_ARBITRARY: 1
    networks:
      - network-mysql

volumes:
  mysql-data:
    name: mysql-data

networks:
  network-mysql:
    driver: bridge
    name: network-mysql