### Register
post http://localhost:8010/api/services
Content-Type: application/json

{
    "name": "ServiceName",
    "host": "localhost",
    "port": 3000,
    "healthCheckUrl": "http://localhost:3000/health"
}

### Get Services
get http://localhost:8010/api/services/name/ServiceName
